spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: ''
    url: jdbc:mysql://localhost:3306/community?useSSL=false&serverTimezone=Asia/Seoul



