spring:
  datasource:
    url: jdbc:mysql://localhost:3306/txsn?characterEncoding=utf-8&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
    #      ddl-auto: create-drop # ?????? ????? ???? ???? ?????. ??????? ?????.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # MySQL 5.x? ????? ??? ?????.
        show_sql: true # ?? ??? ?????.
        format_sql: true # ??? ?? ??? ??????.
  level:
    org.hibernate.SQL: debug # ?? ??? ??? ??? ?????.
logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG


